# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auction.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rauction.proto\"\x06\n\x04Null\"\x15\n\x03\x62id\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x02\"\x1b\n\x07receipt\x12\x10\n\x08received\x18\x01 \x01(\x08\"%\n\x06result\x12\x0b\n\x03win\x18\x01 \x01(\x02\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\x32>\n\x07\x61uction\x12\x18\n\x04\x63\x61ll\x12\x04.bid\x1a\x08.receipt\"\x00\x12\x19\n\x05\x63lose\x12\x05.Null\x1a\x07.result\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NULL']._serialized_start=17
  _globals['_NULL']._serialized_end=23
  _globals['_BID']._serialized_start=25
  _globals['_BID']._serialized_end=46
  _globals['_RECEIPT']._serialized_start=48
  _globals['_RECEIPT']._serialized_end=75
  _globals['_RESULT']._serialized_start=77
  _globals['_RESULT']._serialized_end=114
  _globals['_AUCTION']._serialized_start=116
  _globals['_AUCTION']._serialized_end=178
# @@protoc_insertion_point(module_scope)
