# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auction.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rauction.proto\"\x06\n\x04Null\"\x1b\n\x07receipt\x12\x10\n\x08received\x18\x01 \x01(\x08\"%\n\x06result\x12\x0b\n\x03win\x18\x01 \x01(\x02\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\"\x1a\n\x07testmsg\x12\x0f\n\x07subject\x18\x01 \x01(\t2N\n\x07\x61uction\x12\x1b\n\x04\x63\x61ll\x12\x07.result\x1a\x08.receipt\"\x00\x12&\n\x0etestconnection\x12\x08.testmsg\x1a\x08.receipt\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NULL']._serialized_start=17
  _globals['_NULL']._serialized_end=23
  _globals['_RECEIPT']._serialized_start=25
  _globals['_RECEIPT']._serialized_end=52
  _globals['_RESULT']._serialized_start=54
  _globals['_RESULT']._serialized_end=91
  _globals['_TESTMSG']._serialized_start=93
  _globals['_TESTMSG']._serialized_end=119
  _globals['_AUCTION']._serialized_start=121
  _globals['_AUCTION']._serialized_end=199
# @@protoc_insertion_point(module_scope)
