# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auction.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rauction.proto\"\x06\n\x04Null\"\x1b\n\x07receipt\x12\x10\n\x08received\x18\x01 \x01(\x08\"o\n\x06result\x12\t\n\x01t\x18\x01 \x01(\x02\x12\x13\n\x0bsubject_bid\x18\x02 \x01(\x02\x12\x15\n\ruser_win_flag\x18\x03 \x01(\x08\x12\x16\n\x0e\x63urrent_payout\x18\x04 \x01(\x02\x12\x16\n\x0etotal_winnings\x18\x05 \x01(\x02\"3\n\x06survey\x12\t\n\x01t\x18\x01 \x01(\x02\x12\x11\n\tenjoyment\x18\x02 \x01(\x02\x12\x0b\n\x03rpe\x18\x03 \x01(\x02\"\x1a\n\ttreadmill\x12\r\n\x05state\x18\x01 \x01(\x08\"\x16\n\x07testmsg\x12\x0b\n\x03msg\x18\x01 \x01(\t2\x9c\x01\n\x07\x61uction\x12&\n\x0etestconnection\x12\x08.testmsg\x1a\x08.receipt\"\x00\x12\x1b\n\x04\x63\x61ll\x12\x07.result\x1a\x08.receipt\"\x00\x12\x1f\n\x08question\x12\x07.survey\x1a\x08.receipt\"\x00\x12+\n\x11treadmill_message\x12\n.treadmill\x1a\x08.receipt\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NULL']._serialized_start=17
  _globals['_NULL']._serialized_end=23
  _globals['_RECEIPT']._serialized_start=25
  _globals['_RECEIPT']._serialized_end=52
  _globals['_RESULT']._serialized_start=54
  _globals['_RESULT']._serialized_end=165
  _globals['_SURVEY']._serialized_start=167
  _globals['_SURVEY']._serialized_end=218
  _globals['_TREADMILL']._serialized_start=220
  _globals['_TREADMILL']._serialized_end=246
  _globals['_TESTMSG']._serialized_start=248
  _globals['_TESTMSG']._serialized_end=270
  _globals['_AUCTION']._serialized_start=273
  _globals['_AUCTION']._serialized_end=429
# @@protoc_insertion_point(module_scope)
