# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import exoboot_remote_pb2 as exoboot__remote__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in exoboot_remote_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class exoboot_over_networkStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.set_pause = channel.unary_unary(
                '/exoboot_over_network/set_pause',
                request_serializer=exoboot__remote__pb2.pause.SerializeToString,
                response_deserializer=exoboot__remote__pb2.receipt.FromString,
                _registered_method=True)
        self.set_quit = channel.unary_unary(
                '/exoboot_over_network/set_quit',
                request_serializer=exoboot__remote__pb2.quit.SerializeToString,
                response_deserializer=exoboot__remote__pb2.receipt.FromString,
                _registered_method=True)
        self.set_torque = channel.unary_unary(
                '/exoboot_over_network/set_torque',
                request_serializer=exoboot__remote__pb2.torques.SerializeToString,
                response_deserializer=exoboot__remote__pb2.receipt.FromString,
                _registered_method=True)


class exoboot_over_networkServicer(object):
    """Missing associated documentation comment in .proto file."""

    def set_pause(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_quit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_torque(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_exoboot_over_networkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'set_pause': grpc.unary_unary_rpc_method_handler(
                    servicer.set_pause,
                    request_deserializer=exoboot__remote__pb2.pause.FromString,
                    response_serializer=exoboot__remote__pb2.receipt.SerializeToString,
            ),
            'set_quit': grpc.unary_unary_rpc_method_handler(
                    servicer.set_quit,
                    request_deserializer=exoboot__remote__pb2.quit.FromString,
                    response_serializer=exoboot__remote__pb2.receipt.SerializeToString,
            ),
            'set_torque': grpc.unary_unary_rpc_method_handler(
                    servicer.set_torque,
                    request_deserializer=exoboot__remote__pb2.torques.FromString,
                    response_serializer=exoboot__remote__pb2.receipt.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'exoboot_over_network', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('exoboot_over_network', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class exoboot_over_network(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def set_pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exoboot_over_network/set_pause',
            exoboot__remote__pb2.pause.SerializeToString,
            exoboot__remote__pb2.receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def set_quit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exoboot_over_network/set_quit',
            exoboot__remote__pb2.quit.SerializeToString,
            exoboot__remote__pb2.receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def set_torque(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exoboot_over_network/set_torque',
            exoboot__remote__pb2.torques.SerializeToString,
            exoboot__remote__pb2.receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
