syntax = "proto3";

message Null {};

/* General Communication to Exoboot_Wrapper class
build command: python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. exoboot_remote.proto
*/

message data_stream {
    repeated string logging_data = 1;
}

message receipt {
   bool received = 1;
}

message pause {
    bool mybool = 1;
}

message quit {
    bool mybool = 1;
}

message torques {
    float peak_torque_left = 3;
    float peak_torque_right = 4;
}

service exoboot_over_network{
    rpc set_pause (pause) returns (receipt) {}
    rpc set_quit (quit) returns (receipt) {}
    rpc set_torque (torques) returns (receipt) {}
}
