# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import logging_pb2 as logging__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in logging_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class logStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.testconnection = channel.unary_unary(
                '/log/testconnection',
                request_serializer=logging__pb2.testmsg.SerializeToString,
                response_deserializer=logging__pb2.receipt.FromString,
                _registered_method=True)
        self.treadmill_state = channel.unary_unary(
                '/log/treadmill_state',
                request_serializer=logging__pb2.treadmillstate.SerializeToString,
                response_deserializer=logging__pb2.receipt.FromString,
                _registered_method=True)
        self.chop = channel.unary_unary(
                '/log/chop',
                request_serializer=logging__pb2.beaver.SerializeToString,
                response_deserializer=logging__pb2.receipt.FromString,
                _registered_method=True)
        self.call = channel.unary_unary(
                '/log/call',
                request_serializer=logging__pb2.result.SerializeToString,
                response_deserializer=logging__pb2.receipt.FromString,
                _registered_method=True)
        self.question = channel.unary_unary(
                '/log/question',
                request_serializer=logging__pb2.survey.SerializeToString,
                response_deserializer=logging__pb2.receipt.FromString,
                _registered_method=True)
        self.slider_update = channel.unary_unary(
                '/log/slider_update',
                request_serializer=logging__pb2.slider.SerializeToString,
                response_deserializer=logging__pb2.receipt.FromString,
                _registered_method=True)
        self.presentation_result = channel.unary_unary(
                '/log/presentation_result',
                request_serializer=logging__pb2.presentation.SerializeToString,
                response_deserializer=logging__pb2.receipt.FromString,
                _registered_method=True)
        self.comparison_result = channel.unary_unary(
                '/log/comparison_result',
                request_serializer=logging__pb2.comparison.SerializeToString,
                response_deserializer=logging__pb2.receipt.FromString,
                _registered_method=True)
        self.set_prefix = channel.unary_unary(
                '/log/set_prefix',
                request_serializer=logging__pb2.subject_prefix.SerializeToString,
                response_deserializer=logging__pb2.receipt.FromString,
                _registered_method=True)
        self.set_header = channel.unary_unary(
                '/log/set_header',
                request_serializer=logging__pb2.header.SerializeToString,
                response_deserializer=logging__pb2.receipt.FromString,
                _registered_method=True)
        self.log = channel.unary_unary(
                '/log/log',
                request_serializer=logging__pb2.datastream.SerializeToString,
                response_deserializer=logging__pb2.receipt.FromString,
                _registered_method=True)


class logServicer(object):
    """Missing associated documentation comment in .proto file."""

    def testconnection(self, request, context):
        """General
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def treadmill_state(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def chop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def call(self, request, context):
        """Vickrey Auction Specific
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def question(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def slider_update(self, request, context):
        """VAS Specific
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def presentation_result(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def comparison_result(self, request, context):
        """JND Specific
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_prefix(self, request, context):
        """Logging General
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_header(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def log(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_logServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'testconnection': grpc.unary_unary_rpc_method_handler(
                    servicer.testconnection,
                    request_deserializer=logging__pb2.testmsg.FromString,
                    response_serializer=logging__pb2.receipt.SerializeToString,
            ),
            'treadmill_state': grpc.unary_unary_rpc_method_handler(
                    servicer.treadmill_state,
                    request_deserializer=logging__pb2.treadmillstate.FromString,
                    response_serializer=logging__pb2.receipt.SerializeToString,
            ),
            'chop': grpc.unary_unary_rpc_method_handler(
                    servicer.chop,
                    request_deserializer=logging__pb2.beaver.FromString,
                    response_serializer=logging__pb2.receipt.SerializeToString,
            ),
            'call': grpc.unary_unary_rpc_method_handler(
                    servicer.call,
                    request_deserializer=logging__pb2.result.FromString,
                    response_serializer=logging__pb2.receipt.SerializeToString,
            ),
            'question': grpc.unary_unary_rpc_method_handler(
                    servicer.question,
                    request_deserializer=logging__pb2.survey.FromString,
                    response_serializer=logging__pb2.receipt.SerializeToString,
            ),
            'slider_update': grpc.unary_unary_rpc_method_handler(
                    servicer.slider_update,
                    request_deserializer=logging__pb2.slider.FromString,
                    response_serializer=logging__pb2.receipt.SerializeToString,
            ),
            'presentation_result': grpc.unary_unary_rpc_method_handler(
                    servicer.presentation_result,
                    request_deserializer=logging__pb2.presentation.FromString,
                    response_serializer=logging__pb2.receipt.SerializeToString,
            ),
            'comparison_result': grpc.unary_unary_rpc_method_handler(
                    servicer.comparison_result,
                    request_deserializer=logging__pb2.comparison.FromString,
                    response_serializer=logging__pb2.receipt.SerializeToString,
            ),
            'set_prefix': grpc.unary_unary_rpc_method_handler(
                    servicer.set_prefix,
                    request_deserializer=logging__pb2.subject_prefix.FromString,
                    response_serializer=logging__pb2.receipt.SerializeToString,
            ),
            'set_header': grpc.unary_unary_rpc_method_handler(
                    servicer.set_header,
                    request_deserializer=logging__pb2.header.FromString,
                    response_serializer=logging__pb2.receipt.SerializeToString,
            ),
            'log': grpc.unary_unary_rpc_method_handler(
                    servicer.log,
                    request_deserializer=logging__pb2.datastream.FromString,
                    response_serializer=logging__pb2.receipt.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'log', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('log', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class log(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def testconnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/log/testconnection',
            logging__pb2.testmsg.SerializeToString,
            logging__pb2.receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def treadmill_state(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/log/treadmill_state',
            logging__pb2.treadmillstate.SerializeToString,
            logging__pb2.receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def chop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/log/chop',
            logging__pb2.beaver.SerializeToString,
            logging__pb2.receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/log/call',
            logging__pb2.result.SerializeToString,
            logging__pb2.receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def question(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/log/question',
            logging__pb2.survey.SerializeToString,
            logging__pb2.receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def slider_update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/log/slider_update',
            logging__pb2.slider.SerializeToString,
            logging__pb2.receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def presentation_result(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/log/presentation_result',
            logging__pb2.presentation.SerializeToString,
            logging__pb2.receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def comparison_result(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/log/comparison_result',
            logging__pb2.comparison.SerializeToString,
            logging__pb2.receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def set_prefix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/log/set_prefix',
            logging__pb2.subject_prefix.SerializeToString,
            logging__pb2.receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def set_header(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/log/set_header',
            logging__pb2.header.SerializeToString,
            logging__pb2.receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def log(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/log/log',
            logging__pb2.datastream.SerializeToString,
            logging__pb2.receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
