# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gui2controller.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14gui2controller.proto\"\x06\n\x04Null\"\x95\x01\n\x0b\x64\x61ta_stream\x12\x0c\n\x04time\x18\x01 \x01(\x02\x12\x1f\n\x17\x63urrent_torque_selected\x18\x02 \x01(\x02\x12\x1b\n\x13\x61\x64justed_slider_btn\x18\x03 \x01(\t\x12\x1d\n\x15\x61\x64justed_slider_value\x18\x04 \x01(\x02\x12\x1b\n\x13\x63onfirm_btn_pressed\x18\x05 \x01(\t2>\n\x14\x43ommunicationService\x12&\n\rGUI_Messenger\x12\x0c.data_stream\x1a\x05.Null\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gui2controller_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NULL']._serialized_start=24
  _globals['_NULL']._serialized_end=30
  _globals['_DATA_STREAM']._serialized_start=33
  _globals['_DATA_STREAM']._serialized_end=182
  _globals['_COMMUNICATIONSERVICE']._serialized_start=184
  _globals['_COMMUNICATIONSERVICE']._serialized_end=246
# @@protoc_insertion_point(module_scope)
