#this file is used to define the layout of the GUI
#:import Factory kivy.factory.Factory
#:import utils kivy.utils

#This describes the layout and the orientation of the 10 buttons on the GUI
<GuiVas>:
    GridLayout:
        cols: 2
        size: root.width, root.height

        GridLayout:
            #orientation: 'horizontal'
            cols:3
            size_hint_y: 1
            size_hint_x: 0.7

            BoxLayout:
                id: left_label
                orientation: 'vertical'
                size_hint_x: 0.2
                Label:
                    text:'Assistance\nNot Valued:\n$-15' 
                    halign: 'center'
                    valign: 'center'
                    text_size: self.size
                    font_name: 'Roboto'

            BoxLayout:
                id: slider_layout
                orientation: 'vertical'
                size_hint_y: 0.8
                on_kv_post: root.create_sliders()

            BoxLayout:
                id: right_label
                orientation: 'vertical'
                size_hint_x: 0.2
                Label:
                    text: 'Assistance Valued:\n$50' 
                    halign: 'center'
                    valign: 'center'
                    text_size: self.size
                    font_name: 'Roboto'

        BoxLayout:
            id: button_layout
            orientation: 'vertical'
            size_hint_y: 0.8
            size_hint_x: 0.3
            on_kv_post: root.create_buttons()