# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Message_pb2 as Message__pb2


class GUIStub(object):
    """
    GUI: (Client running on the surface tablet) -- This will send the user selection (which is basically the torque values)
    Controller: (Server running on the assisitve devices attached to the RPI)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UserButton = channel.unary_unary(
                '/GUI/UserButton',
                request_serializer=Message__pb2.Input.SerializeToString,
                response_deserializer=Message__pb2.Null.FromString,
                )


class GUIServicer(object):
    """
    GUI: (Client running on the surface tablet) -- This will send the user selection (which is basically the torque values)
    Controller: (Server running on the assisitve devices attached to the RPI)
    """

    def UserButton(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GUIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UserButton': grpc.unary_unary_rpc_method_handler(
                    servicer.UserButton,
                    request_deserializer=Message__pb2.Input.FromString,
                    response_serializer=Message__pb2.Null.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GUI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GUI(object):
    """
    GUI: (Client running on the surface tablet) -- This will send the user selection (which is basically the torque values)
    Controller: (Server running on the assisitve devices attached to the RPI)
    """

    @staticmethod
    def UserButton(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GUI/UserButton',
            Message__pb2.Input.SerializeToString,
            Message__pb2.Null.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
