# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rMessage.proto\"\x06\n\x04Null\"\x17\n\x05Input\x12\x0e\n\x06torque\x18\x01 \x01(\x02\x32$\n\x03GUI\x12\x1d\n\nUserButton\x12\x06.Input\x1a\x05.Null\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NULL']._serialized_start=17
  _globals['_NULL']._serialized_end=23
  _globals['_INPUT']._serialized_start=25
  _globals['_INPUT']._serialized_end=48
  _globals['_GUI']._serialized_start=50
  _globals['_GUI']._serialized_end=86
# @@protoc_insertion_point(module_scope)
