# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message_2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fMessage_2.proto\"\x06\n\x04Null\"\x1d\n\x07Request\x12\x12\n\ndata_array\x18\x01 \x03(\x02\x32\x32\n\x14\x43ommunicationService\x12\x1a\n\x05Input\x12\x08.Request\x1a\x05.Null\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Message_2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NULL._serialized_start=19
  _NULL._serialized_end=25
  _REQUEST._serialized_start=27
  _REQUEST._serialized_end=56
  _COMMUNICATIONSERVICE._serialized_start=58
  _COMMUNICATIONSERVICE._serialized_end=108
# @@protoc_insertion_point(module_scope)
