# Snippets of .kv code that was used to make my slider           
           
           orientation: 'vertical'
           GridLayout:
                cols: 5
                rows: 1

                Button:
                    id: A
                    text: "A"
                    font_size:64
                    on_release:root.press('A')
                    background_normal: ''
                    background_color: utils.get_color_from_hex('#0d9c35')
                Button:
                    id: B
                    text: "B"
                    font_size:64
                    on_release:root.press('B')
                    background_normal: ''
                    background_color: utils.get_color_from_hex('#00954b')

                Button:
                    id: C
                    text: "C"
                    font_size:64
                    on_release:root.press('C')
                    background_normal: ''
                    background_color: utils.get_color_from_hex('#92dc7e')

                Button:
                    id: D
                    text: "D"
                    font_size:64
                    on_release:root.press('D')
                    background_normal: ''
                    background_color: utils.get_color_from_hex('#64c987')
                Button:
                    id: E
                    text: "E"
                    font_size:64
                    on_release:root.press('E')
                    background_normal: ''
                    background_color: utils.get_color_from_hex('#39b48e')






            Slider:
                orientation: 'horizontal'
                id: vas
                min: -15   # VAS starting val
                max: 50    # VAS ending val
                value: 0   # initial position of slider
                orientation: 'horizontal'
                on_value: root.on_slider_value(vas.value)
                cursor_image: 'pin_2.png'  # Custom cursor image
                cursor_size: (35, 35)  # Custom cursor size

                # specifies position of the cursor label
                on_touch_down: cursor_label.center_x = args[1].x; cursor_label.y = 25+vas.center_y  # Adjust the position of the label when the touch starts
                on_touch_move: cursor_label.center_x = args[1].x; cursor_label.y = vas.center_y + vas.height / 22  # Adjust the position of the label when the touch moves
                
                # corresponding cursor label
                Label:
                    id: cursor_label
                    text: '$'+str(round(vas.value,2))
                    size_hint: None, None
                    size: self.texture_size
                    color: '#0d9c35' # set label to same color as A
                    
                    # Adds a background to the linked cursor label
                    canvas.before:
                        Color:
                            rgba: utils.get_color_from_hex('#07485B')
                        Rectangle:
                            pos: self.pos
                            size: self.size





#this file is used to define the layout of the GUI
#:import Factory kivy.factory.Factory
#:import utils kivy.utils

#This describes the layout and the orientation of the 10 buttons on the GUI
<GuiVas>:
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        
        BoxLayout:
            size_hint_y: 0.5
            orientation: 'horizontal'

            Label:
                text:'Not\nValuable:\n$15' 
                size_hint_x: 0.08
                halign: 'center'
                valign: 'center'
                text_size: self.size
                font_name: 'Roboto'
                font_size: 30 

            Slider:
                orientation: 'horizontal'
                id: vas
                min: -15   # VAS starting val
                max: 50    # VAS ending val
                value: 0   # initial position of slider
                orientation: 'horizontal'
                on_value: root.on_slider_value(vas.value)
                cursor_image: 'pin_2.png'  # Custom cursor image
                cursor_size: (35, 35)  # Custom cursor size

                # specifies position of the cursor label
                on_touch_down: cursor_label.center_x = args[1].x; cursor_label.y = 25+vas.center_y  # Adjust the position of the label when the touch starts
                on_touch_move: cursor_label.center_x = args[1].x; cursor_label.y = vas.center_y + vas.height / 22  # Adjust the position of the label when the touch moves
                
                # corresponding cursor label
                Label:
                    id: cursor_label
                    text: '$'+str(round(vas.value,2))
                    size_hint: None, None
                    size: self.texture_size
                    color: '#0d9c35' # set label to same color as A
                    
                    # Adds a background to the linked cursor label
                    canvas.before:
                        Color:
                            rgba: utils.get_color_from_hex('#07485B')
                        Rectangle:
                            pos: self.pos
                            size: self.size
            
            Label:
                text: 'Valuable:\n$50' 
                size_hint_x: 0.08
                halign: 'center'
                valign: 'center'
                text_size: self.size
                font_name: 'Roboto'
                font_size: 30 


        BoxLayout:
            id: button_layout
            size_hint_y: 0.5
            rows: 1

            on_kv_post: root.create_buttons()


















            BoxLayout:
                id: left_right_labels
                orientation: 'horizontal'
                size_hint_y: 0.2

                Label:
                    text:'Not\nValuable:\n$15' 
                    halign: 'center'
                    valign: 'center'
                    text_size: self.size
                    font_name: 'Roboto'
                    font_size: 30 

                Label:
                    text: 'Valuable:\n$50' 
                    halign: 'center'
                    valign: 'center'
                    text_size: self.size
                    font_name: 'Roboto'
                    font_size: 30 

                