# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gui2controller2.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15gui2controller2.proto\"\x06\n\x04Null\"#\n\x0b\x64\x61ta_stream\x12\x14\n\x0clogging_data\x18\x01 \x03(\t2>\n\x14\x43ommunicationService\x12&\n\rGUI_Messenger\x12\x0c.data_stream\x1a\x05.Null\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gui2controller2_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NULL']._serialized_start=25
  _globals['_NULL']._serialized_end=31
  _globals['_DATA_STREAM']._serialized_start=33
  _globals['_DATA_STREAM']._serialized_end=68
  _globals['_COMMUNICATIONSERVICE']._serialized_start=70
  _globals['_COMMUNICATIONSERVICE']._serialized_end=132
# @@protoc_insertion_point(module_scope)
